[package]
name = "sick"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
log = "0.4"
tokio = { version = "1", features = ["io-util", "macros"] }

[dev-dependencies]
anyhow = "1"
tokio = { version = "1", features = [
    "io-util",
    "macros",
    "sync",
    "rt",
    "rt-multi-thread",
    "net",
] }

[[example]]
name = "ref_message"
